steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args: [ '-c', 'docker login docker.io --username=yeneek --password=$_DOCKER_PASSWORD' ]
  - name: gcr.io/cloud-builders/docker
    args:
      - pull
      - yeneek/kremen-webpage:latest
  - name: gcr.io/cloud-builders/docker
    args:
      - build
#      - --cache-from=yeneek/kremen-webpage:latest
      - --tag=yeneek/kremen-webpage:$BUILD_ID
      - --tag=yeneek/kremen-webpage:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - docker.io/yeneek/kremen-webpage:latest
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - docker.io/yeneek/kremen-webpage:$BUILD_ID
  # here is, where deployment starts
#  - name: gcr.io/cloud-builders/gcloud
#    entrypoint: 'bash'
#    args:
#      - -c
#      - gcloud secrets versions access $_SECRET_VERSION --secret kubeconfig > /workspace/kubeconfig.yml
#  - name: gcr.io/cloud-builders/kubectl
#    entrypoint: kubectl
#    env:
#      - KUBECONFIG=/workspace/kubeconfig.yml
#    args:
#      - -n
#      - kremen-personal
#      - set
#      - image
#      - deployment/kremen-webpage
#      - webpage=yeneek/kremen-webpage:$BUILD_ID
timeout: 1500s
substitutions:
  _DOCKER_PASSWORD: provide password
  _SECRET_VERSION: "1"
